const {
  ebt_School_Result,
  ebt_Friend_Result,
  ebt_Family_Result,
  ebt_Mood_Result,
  ebt_Unrest_Result,
  ebt_Sad_Result,
  ebt_Health_Result,
  ebt_Attention_Result,
  ebt_Movement_Result,
  ebt_Angry_Result,
  ebt_Self_Result,
} = require("../DB/psy_test");

// Database Table Info
const User_Table_Info = {
  table: "soyes_ai_User",
  attribute: {
    pKey: "uid",
    attr1: "Email",
    attr2: "passWard",
    attr3: "name",
    attr4: "phoneNumber",
    attr5: "oauth_type",
    attr6: "creation_date",
    attr7: "lastLogin_date",
  },
};
const EBT_Table_Info = {
  School: {
    table: "soyes_ai_Ebt_School",
    attribute: {
      pKey: "uid",
      attr1: "school_question_0",
      attr2: "school_question_1",
      attr3: "school_question_2",
      attr4: "school_question_3",
      attr5: "school_question_4",
      attr6: "school_question_5",
      attr7: "chat",
      attr8: "date",
    },
    result: ebt_School_Result, // 적용 프롬프트
    danger_score: 7.6,
    caution_score: 6.5,
  },
  Friend: {
    table: "soyes_ai_Ebt_Friend",
    attribute: {
      pKey: "uid",
      attr1: "friend_question_0",
      attr2: "friend_question_1",
      attr3: "friend_question_2",
      attr4: "friend_question_3",
      attr5: "friend_question_4",
      attr6: "friend_question_5",
      attr7: "friend_question_6",
      attr8: "friend_question_7",
      attr9: "chat",
      attr10: "date",
    },
    result: ebt_Friend_Result,
    danger_score: 9.6,
    caution_score: 8.2,
  },
  Family: {
    table: "soyes_ai_Ebt_Family",
    attribute: {
      pKey: "uid",
      attr1: "family_question_0",
      attr2: "family_question_1",
      attr3: "family_question_2",
      attr4: "family_question_3",
      attr5: "family_question_4",
      attr6: "family_question_5",
      attr7: "family_question_6",
      attr8: "chat",
      attr9: "date",
    },
    result: ebt_Family_Result,
    danger_score: 8,
    caution_score: 7,
  },
  Mood: {
    table: "soyes_ai_Ebt_Mood",
    attribute: {
      pKey: "uid",
      attr1: "mood_question_0",
      attr2: "mood_question_1",
      attr3: "mood_question_2",
      attr4: "chat",
      attr5: "date",
    },
    result: ebt_Mood_Result,
    danger_score: 5,
    caution_score: 4,
  },
  Unrest: {
    table: "soyes_ai_Ebt_Unrest",
    attribute: {
      pKey: "uid",
      attr1: "unrest_question_0",
      attr2: "unrest_question_1",
      attr3: "unrest_question_2",
      attr4: "unrest_question_3",
      attr5: "unrest_question_4",
      attr6: "unrest_question_5",
      attr7: "chat",
      attr8: "date",
    },
    result: ebt_Unrest_Result,
    danger_score: 10,
    caution_score: 9,
  },
  Sad: {
    table: "soyes_ai_Ebt_Sad",
    attribute: {
      pKey: "uid",
      attr1: "sad_question_0",
      attr2: "sad_question_1",
      attr3: "sad_question_2",
      attr4: "sad_question_3",
      attr5: "sad_question_4",
      attr6: "sad_question_5",
      attr7: "sad_question_6",
      attr8: "chat",
      attr9: "date",
    },
    result: ebt_Sad_Result,
    danger_score: 10,
    caution_score: 9,
  },
  Health: {
    table: "soyes_ai_Ebt_Health",
    attribute: {
      pKey: "uid",
      attr1: "health_question_0",
      attr2: "health_question_1",
      attr3: "health_question_2",
      attr4: "health_question_3",
      attr5: "health_question_4",
      attr6: "chat",
      attr7: "date",
    },
    result: ebt_Health_Result,
    danger_score: 7,
    caution_score: 6,
  },
  Attention: {
    table: "soyes_ai_Ebt_Attention",
    attribute: {
      pKey: "uid",
      attr1: "attention_question_0",
      attr2: "attention_question_1",
      attr3: "attention_question_2",
      attr4: "attention_question_3",
      attr5: "attention_question_4",
      attr6: "attention_question_5",
      attr7: "attention_question_6",
      attr8: "chat",
      attr9: "date",
    },
    result: ebt_Attention_Result,
    danger_score: 11,
    caution_score: 9,
  },
  Movement: {
    table: "soyes_ai_Ebt_Movement",
    attribute: {
      pKey: "uid",
      attr1: "movement_question_0",
      attr2: "movement_question_1",
      attr3: "movement_question_2",
      attr4: "movement_question_3",
      attr5: "movement_question_4",
      attr6: "movement_question_5",
      attr7: "movement_question_6",
      attr8: "chat",
      attr9: "date",
    },
    result: ebt_Movement_Result,
    danger_score: 8,
    caution_score: 7,
  },
  Angry: {
    table: "soyes_ai_Ebt_Angry",
    attribute: {
      pKey: "uid",
      attr1: "angry_question_0",
      attr2: "angry_question_1",
      attr3: "angry_question_2",
      attr4: "angry_question_3",
      attr5: "angry_question_4",
      attr6: "angry_question_5",
      attr7: "chat",
      attr8: "date",
    },
    result: ebt_Angry_Result,
    danger_score: 8,
    caution_score: 7,
  },
  Self: {
    table: "soyes_ai_Ebt_Self",
    attribute: {
      pKey: "uid",
      attr1: "self_question_0",
      attr2: "self_question_1",
      attr3: "self_question_2",
      attr4: "self_question_3",
      attr5: "self_question_4",
      attr6: "chat",
      attr7: "date",
    },
    result: ebt_Self_Result,
    danger_score: 7.1,
    caution_score: 5.9,
  },
  Log: {
    table: "soyes_ai_User_Ebt_Log",
    attribute: {
      cKey: "uid",
      attr1: "date",
      attr2: "ebt_analysis",
      attr3: "ebt_type",
    },
  },
};
const PT_Table_Info = {
  Main: {
    table: "soyes_ai_PT",
    attribute: {
      pKey: "uid",
      attr1: "date",
      attr2: "persanl_result",
      attr3: "chat",
    },
  },

  Log: {
    table: "soyes_ai_User_Pt_Log",
    attribute: {
      cKey: "uid",
      attr1: "date",
      attr2: "persanl_result",
      attr3: "pt_analysis",
    },
  },
};
const Consult_Log_Table_Info = {
  Log: {
    table: "soyes_ai_User_Consult_Log",
    attribute: {
      pKey: "uid",
      attr1: "date",
      attr2: "avarta_name",
      attr3: "consult_log",
    },
  },
};

module.exports = {
  User_Table_Info,
  EBT_Table_Info,
  PT_Table_Info,
  Consult_Log_Table_Info,
};
